name: Build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - debian/changelog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: make all deb
