name: Build & Release
on:
  workflow_dispatch:
  push:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        run: |
          make test
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get build-dep --no-install-recommends -y .
          make all deb
      - name: Check if the latest version is releasable
        run: |
          echo "distro=$(dpkg-parsechangelog -S Distribution)" >> $GITHUB_ENV
          echo "version=$(dpkg-parsechangelog -S Version)" >> $GITHUB_ENV
      - name: Release
        if: env.distro != 'UNRELEASED'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
          files: |
            ../*.deb
